redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Downloads\\smart-office-deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/ai-employee-form"
to = "/ai-employee-form.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]